logging:
  level:
    org:
      atmosphere: warn

vaadin:
  pnpm-enabled: false

spring:
  config:
    activate:
      on-profile: production
  datasource:
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
